---
version: "{build}"

clone_folder: c:\gopath\src\github.com\exercism\cli

environment:
  GOPATH: c:\gopath

init:
  - git config --global core.autocrlf input

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -u github.com/golang/dep/cmd/dep
  - c:\gopath\bin\dep.exe ensure

build_script:
  - go test -cover ./...
